apiVersion: 1

datasources:
  - name: BuildHistory
    uid: buildhistory
    type: postgres
    access: proxy
    url: postgres:5432
    user: builduser
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: buildhistory
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: false